.github/workflows/scip.yml: SRC_ACCESS_TOKEN added as it was missing from the scip.yml.
```
unauthorized upload

A Sourcegraph access token must be provided via SRC_ACCESS_TOKEN for uploading SCIP data.
For more details, see https://sourcegraph.com/docs/cli/how-tos/creating_an_access_token.
Error: Process completed with exit code 1.
```